apiVersion: v1
kind: Service
metadata:
  name: patch-k8s-server
  namespace: datatunerx-dev
spec:
  selector:
    app: patch-k8s-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
